[Paths]
sdcc_bin = ~/Pinguino/v13/pinguino-compilers/linux64/p8/bin
gcc_bin = ~/Pinguino/v13/pinguino-compilers/linux64/p32/bin
xc8_bin = /opt/microchip/xc8/v2.10/bin
pinguino_8_libs = ~/Pinguino/v13/pinguino-libraries/p8
pinguino_32_libs = ~/Pinguino/v13/pinguino-libraries/p32
install_path = ~/Pinguino/v13/pinguino-ide
user_path = ~/.pinguino/v13
user_libs = ~/.pinguino/v13/pinguinolibs
